---
inherit: base.yml
applications:
- name: crime-data-explorer
  host: crime-data-explorer
  buildpack: nodejs_buildpack
  memory: 256M
  disk_quota: 256M
  domain: fr.cloud.gov
env:
  CDE_API: 'https://crime-data-api.fr.cloud.gov'
services:
  - crime-data-api-key-development
